import json
import sys
from pathlib import Path


SUPPORTED_EVIDENCE = {
    "CCTV",
    "DNA",
    "FINGERPRINT",
    "GPS",
    "ACCESS_LOG",
    "FINANCIAL",
    "COMMUNICATION",
    "WITNESS",
    "DIGITAL",
    "DOCUMENT",
}


# ============================================================
# BASIC HELPERS
# ============================================================

def parse_key_value_text(text):
    """
    Convert simple extracted text such as:

        ID: P001
        Name: Arvind Malhotra
        Role: property owner

    into a dictionary.
    """

    result = {}

    if not isinstance(text, str):
        return result

    for line in text.splitlines():
        line = line.strip()

        if ":" not in line:
            continue

        key, value = line.split(":", 1)

        key = key.strip().lower().replace(" ", "_")
        value = value.strip()

        if value:
            result[key] = value

    return result


def safe_float(value):
    """Convert a value to float safely."""

    if value is None or value == "":
        return None

    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def safe_int(value):
    """Convert a value to int safely."""

    if value is None or value == "":
        return None

    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def flatten(value):
    """
    Flatten nested lists generated by normalizers.
    """

    if value is None:
        return []

    if isinstance(value, list):
        result = []

        for item in value:
            result.extend(flatten(item))

        return result

    return [value]


def make_source_evidence(
    source_file,
    evidence_type,
    description,
    base_confidence,
    attributes=None,
):
    """
    Standard evidence structure.
    """

    return {
        "evidence": {
            "type": evidence_type,
            "description": description,
            "base_confidence": base_confidence,
            "attributes": attributes or {},
        },
        "source_file": source_file,
    }


# ============================================================
# CASE
# ============================================================

def normalize_case_context(source_file, content):
    data = parse_key_value_text(content)

    return {
        "case": {
            "case_reference": data.get(
                "case_id",
                "MH-2026-0818",
            ),
            "title": "The Meridian House Incident",
            "incident_time": None,
            "incident_location": data.get(
                "incident_location"
            ),
            "status": "OPEN",
            "metadata": {
                "primary_site": data.get("primary_site"),
                "incident_window": data.get(
                    "incident_window"
                ),
                "victim": data.get("victim"),
                "initial_report": data.get(
                    "initial_report"
                ),
            },
        },
        "source_file": source_file,
    }


# ============================================================
# PERSON
# ============================================================

def normalize_person(source_file, content):
    data = parse_key_value_text(content)

    entity_id = data.get("id")

    if not entity_id:
        return None

    return {
        "entity": {
            "external_reference": entity_id,
            "display_name": data.get(
                "name",
                entity_id,
            ),
            "entity_type": "PERSON",
            "attributes": {
                "role": data.get("role"),
                "context": data.get("context"),
            },
        },
        "source_file": source_file,
    }


# ============================================================
# LOCATION
# ============================================================

def normalize_location(source_file, content):
    """
    Normalize location TXT files.

    Example:

        LOCATION
        L001
        Meridian House
        Type: mixed-use heritage property

    """

    if not isinstance(content, str):
        return None

    lines = [
        line.strip()
        for line in content.splitlines()
        if line.strip()
    ]

    location_id = None
    location_name = None
    location_type = None

    for line in lines:

        if line.startswith("L") and len(line) <= 10:
            location_id = line

        elif line.lower().startswith("type:"):
            location_type = line.split(
                ":",
                1
            )[1].strip()

    # Find location name.
    if location_id:
        try:
            index = lines.index(location_id)

            if index + 1 < len(lines):
                location_name = lines[index + 1]

        except ValueError:
            pass

    if not location_id:
        data = parse_key_value_text(content)

        location_id = data.get("id")
        location_name = data.get(
            "name",
            location_id,
        )

    if not location_id:
        return None

    return {
        "location": {
            "external_reference": location_id,
            "location_name": (
                location_name
                or location_id
            ),
            "location_type": location_type,
            "address": None,
            "latitude": None,
            "longitude": None,
            "attributes": {
                "source_format": "site_plan_text",
            },
        },
        "source_file": source_file,
    }


# ============================================================
# GEOJSON
# ============================================================

def normalize_geojson_locations(
    source_file,
    content,
):
    """
    Normalize GeoJSON location coordinates.

    Coordinates are stored as:

        longitude, latitude
    """

    if not isinstance(content, dict):
        return None

    features = content.get("features", [])

    results = []

    for feature in features:

        if not isinstance(feature, dict):
            continue

        properties = feature.get(
            "properties",
            {}
        )

        geometry = feature.get(
            "geometry",
            {}
        )

        location_id = properties.get(
            "location_id"
        )

        coordinates = geometry.get(
            "coordinates",
            []
        )

        if not location_id:
            continue

        longitude = None
        latitude = None

        if (
            isinstance(coordinates, list)
            and len(coordinates) >= 2
        ):
            longitude = safe_float(
                coordinates[0]
            )

            latitude = safe_float(
                coordinates[1]
            )

        results.append({
            "location_geometry": {
                "external_reference": location_id,
                "latitude": latitude,
                "longitude": longitude,
                "geometry_type": geometry.get(
                    "type"
                ),
            },
            "source_file": source_file,
        })

    return results


# ============================================================
# KML
# ============================================================

def normalize_kml_locations(
    source_file,
    content,
):
    """
    Normalize extracted KML places.

    Example:

        {
            "name": "L001",
            "coordinates": "85.82,20.29,0"
        }
    """

    if not isinstance(content, dict):
        return None

    places = content.get(
        "places",
        []
    )

    results = []

    for place in places:

        if not isinstance(place, dict):
            continue

        location_id = place.get("name")

        coordinate_string = place.get(
            "coordinates",
            ""
        )

        parts = coordinate_string.split(",")

        longitude = None
        latitude = None

        if len(parts) >= 2:

            longitude = safe_float(
                parts[0]
            )

            latitude = safe_float(
                parts[1]
            )

        if not location_id:
            continue

        results.append({
            "location_geometry": {
                "external_reference": location_id,
                "latitude": latitude,
                "longitude": longitude,
                "geometry_type": "Point",
            },
            "source_file": source_file,
        })

    return results


# ============================================================
# COMMUNICATIONS
# ============================================================

def normalize_call(source_file, content):

    if not isinstance(content, dict):
        return None

    return {
        "communication": {
            "external_reference": content.get(
                "call_id"
            ),
            "type": "CALL",
            "sender": content.get(
                "caller"
            ),
            "receiver": content.get(
                "receiver"
            ),
            "start_time": content.get(
                "start_time"
            ),
            "duration_seconds": safe_int(
                content.get(
                    "duration_seconds"
                )
            ),
            "status": content.get(
                "status"
            ),
            "content": None,
            "attributes": {},
        },
        "source_file": source_file,
    }


def normalize_message(
    source_file,
    content,
):
    if not isinstance(content, dict):
        return None

    return {
        "communication": {
            "external_reference": content.get(
                "message_id"
            ),
            "type": "CHAT",
            "sender": content.get(
                "sender"
            ),
            "receiver": content.get(
                "receiver"
            ),
            "start_time": content.get(
                "time"
            ),
            "duration_seconds": None,
            "status": None,
            "content": content.get(
                "body"
            ),
            "attributes": {},
        },
        "source_file": source_file,
    }


def normalize_email(
    source_file,
    content,
):
    if not isinstance(content, dict):
        return None

    sender = content.get("from")
    receiver = content.get("to")

    if sender and "@" in sender:
        sender = sender.split(
            "@",
            1
        )[0]

    if receiver and "@" in receiver:
        receiver = receiver.split(
            "@",
            1
        )[0]

    return {
        "communication": {
            "external_reference": content.get(
                "message_id"
            ),
            "type": "EMAIL",
            "sender": sender,
            "receiver": receiver,
            "start_time": content.get(
                "date"
            ),
            "duration_seconds": None,
            "status": None,
            "content": content.get(
                "body"
            ),
            "attributes": {
                "subject": content.get(
                    "subject"
                ),
                "cc": content.get(
                    "cc"
                ),
            },
        },
        "source_file": source_file,
    }


# ============================================================
# TRANSACTIONS
# ============================================================

def normalize_transaction(
    source_file,
    content,
):
    if not isinstance(content, dict):
        return None

    sender = (
        content.get(
            "sender_entity_id"
        )
        or content.get("sender")
    )

    receiver = (
        content.get(
            "receiver_entity_id"
        )
        or content.get("receiver")
    )

    return {
        "transaction": {
            "external_reference": content.get(
                "transaction_id"
            ),
            "sender": sender,
            "receiver": receiver,
            "amount": safe_float(
                content.get("amount")
            ),
            "currency": content.get(
                "currency"
            ),
            "transaction_type": content.get(
                "type"
            ),
            "transaction_time": content.get(
                "timestamp"
            ),
            "attributes": {},
        },
        "source_file": source_file,
    }


# ============================================================
# VEHICLES
# ============================================================

def normalize_vehicle_registry(
    source_file,
    content,
):
    if not isinstance(content, dict):
        return None

    return {
        "vehicle": {
            "external_reference": content.get(
                "vehicle_id"
            ),
            "registration_reference": content.get(
                "plate"
            ),
            "vehicle_type": None,
            "make_model": content.get(
                "description"
            ),
            "associated_entity": content.get(
                "associated_person"
            ),
            "attributes": {},
        },
        "source_file": source_file,
    }


def normalize_vehicle_sighting(
    source_file,
    content,
):
    if not isinstance(content, dict):
        return None

    return {
        "vehicle_sighting": {
            "vehicle": content.get(
                "vehicle_id"
            ),
            "location": content.get(
                "location_id"
            ),
            "observed_at": content.get(
                "time"
            ),
            "confidence_score": 0.80,
            "attributes": {},
        },
        "source_file": source_file,
    }


# ============================================================
# GPS / MOVEMENT
# ============================================================

def make_gps_event(
    source_file,
    entity_id,
    point,
    device_id=None,
    device_type=None,
):
    return {
        "event": {
            "type": "MOVEMENT",
            "entity": entity_id,
            "event_time": point.get(
                "time"
            ),
            "description": (
                "Device location observation"
            ),
            "attributes": {
                "latitude": safe_float(
                    point.get("lat")
                ),
                "longitude": safe_float(
                    point.get("lon")
                ),
                "accuracy_m": safe_float(
                    point.get("accuracy_m")
                ),
                "device_id": device_id,
                "device_type": device_type,
                "point_id": point.get(
                    "point_id"
                ),
            },
        },
        "evidence": {
            "type": "GPS",
            "description": (
                "Extracted device location point"
            ),
            "base_confidence": 0.80,
            "attributes": point,
        },
        "source_file": source_file,
    }


def normalize_gps(
    source_file,
    content,
):
    if not isinstance(content, dict):
        return None

    entity_id = content.get(
        "entity_id"
    )

    artifacts = content.get(
        "artifacts",
        {}
    )

    points = artifacts.get(
        "location_points",
        []
    )

    results = []

    for point in points:

        if not isinstance(point, dict):
            continue

        results.append(
            make_gps_event(
                source_file,
                entity_id,
                point,
                content.get(
                    "device_id"
                ),
                content.get(
                    "device_type"
                ),
            )
        )

    return results


def normalize_gps_csv(
    source_file,
    content,
):
    if not isinstance(content, list):
        return None

    results = []

    for row in content:

        if not isinstance(row, dict):
            continue

        point = {
            "point_id": row.get(
                "point_id"
            ),
            "time": row.get(
                "timestamp"
            ),
            "lat": row.get(
                "lat"
            ),
            "lon": row.get(
                "lon"
            ),
            "accuracy_m": row.get(
                "accuracy_m"
            ),
        }

        results.append(
            make_gps_event(
                source_file,
                row.get("entity_id"),
                point,
            )
        )

    return results


# ============================================================
# ACCESS LOG
# ============================================================

def normalize_access_log(
    source_file,
    content,
):
    """
    Convert each access-log line into an actual event.

    Example:

        2026-08-18 20:54:11 ACCESS L001 EAST_DOOR P005 GRANTED

    """

    if not isinstance(content, str):
        return None

    results = []

    for line in content.splitlines():

        line = line.strip()

        if not line:
            continue

        parts = line.split()

        if len(parts) < 4:
            continue

        date_part = parts[0]
        time_part = parts[1]

        event_time = (
            f"{date_part}T{time_part}"
        )

        event_keyword = parts[2]

        location_id = (
            parts[3]
            if len(parts) > 3
            else None
        )

        remaining = parts[4:]

        entity_id = None

        for token in remaining:

            if (
                isinstance(token, str)
                and token.startswith("P")
                and token[1:].isdigit()
            ):
                entity_id = token
                break

        status = (
            remaining[-1]
            if remaining
            else None
        )

        results.append({
            "event": {
                "type": (
                    "ALARM"
                    if event_keyword == "ALARM"
                    else "ACCESS"
                ),
                "entity": entity_id,
                "event_time": event_time,
                "description": line,
                "attributes": {
                    "location_reference": location_id,
                    "event_keyword": event_keyword,
                    "status": status,
                    "raw_line": line,
                },
            },
            "evidence": {
                "type": "ACCESS_LOG",
                "description": line,
                "base_confidence": 0.82,
                "attributes": {
                    "location_reference": location_id,
                    "entity_reference": entity_id,
                    "raw_line": line,
                },
            },
            "source_file": source_file,
        })

    return results


# ============================================================
# CALENDAR / MEETING
# ============================================================

def normalize_calendar_event(
    source_file,
    content,
):
    if not isinstance(content, dict):
        return None

    event = content.get(
        "event",
        {}
    )

    if not isinstance(event, dict):
        return None

    return {
        "event": {
            "type": "MEETING",
            "event_time": event.get(
                "start"
            ),
            "end_time": event.get(
                "end"
            ),
            "location_reference": event.get(
                "location"
            ),
            "description": event.get(
                "summary"
            ),
            "attributes": {
                "uid": event.get(
                    "uid"
                ),
                "summary": event.get(
                    "summary"
                ),
            },
        },
        "evidence": {
            "type": "DOCUMENT",
            "description": (
                event.get(
                    "summary"
                )
                or "Calendar meeting"
            ),
            "base_confidence": 0.60,
            "attributes": {
                "uid": event.get(
                    "uid"
                ),
                "start": event.get(
                    "start"
                ),
                "end": event.get(
                    "end"
                ),
                "location": event.get(
                    "location"
                ),
            },
        },
        "source_file": source_file,
    }


# ============================================================
# WITNESS
# ============================================================

def normalize_witness(
    source_file,
    content,
):
    result = normalize_generic_document(
        source_file,
        content,
    )

    if result:
        result["evidence"]["type"] = (
            "WITNESS"
        )

        result["evidence"][
            "base_confidence"
        ] = 0.55

    return result


# ============================================================
# GENERIC DOCUMENT
# ============================================================

def normalize_generic_document(
    source_file,
    content,
):
    """
    Preserve unsupported/irregular material
    instead of throwing it away.
    """

    if isinstance(content, str):
        description = content.strip()

    else:
        try:
            description = json.dumps(
                content,
                ensure_ascii=False,
            )
        except (TypeError, ValueError):
            description = str(content)

    if not description:
        return None

    return {
        "evidence": {
            "type": "DOCUMENT",
            "description": description,
            "base_confidence": 0.60,
            "attributes": {},
        },
        "source_file": source_file,
    }


# ============================================================
# MAIN RECORD ROUTER
# ============================================================

def normalize_record(record):

    source_file = record.get(
        "source_file",
        ""
    )

    extension = record.get(
        "extension",
        ""
    ).lower()

    data = record.get(
        "data",
        {}
    )

    if not record.get(
        "success",
        False
    ):
        return None

    content = (
        data.get("content")
        if isinstance(data, dict)
        else data
    )

    data_type = (
        data.get("type", "")
        if isinstance(data, dict)
        else ""
    )

    source_upper = source_file.upper()

    # --------------------------------------------------------
    # NEVER INGEST EVALUATION MATERIAL
    # --------------------------------------------------------

    if source_upper.startswith(
        "14_EVALUATION_ONLY\\"
    ):
        return None

    # --------------------------------------------------------
    # CASE
    # --------------------------------------------------------

    if source_upper.startswith(
        "00_CASE_CONTEXT\\"
    ):
        return normalize_case_context(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # PERSON PROFILES
    # --------------------------------------------------------

    if (
        "\\PERSON_PROFILES\\"
        in source_upper
    ):
        return normalize_person(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # LOCATIONS - TXT
    # --------------------------------------------------------

    if (
        "\\03_LOCATIONS\\"
        in source_upper
        and "\\SITE_PLANS\\"
        in source_upper
    ):
        return normalize_location(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # LOCATIONS - GEOJSON
    # --------------------------------------------------------

    if extension == ".geojson":
        return normalize_geojson_locations(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # LOCATIONS - KML
    # --------------------------------------------------------

    if extension == ".kml":
        return normalize_kml_locations(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # CALL RECORDS
    # --------------------------------------------------------

    if (
        "\\CALL_RECORDS\\"
        in source_upper
    ):

        if isinstance(content, list):

            return [
                normalize_call(
                    source_file,
                    row,
                )
                for row in content
            ]

        return normalize_call(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # MESSAGES CSV
    # --------------------------------------------------------

    if source_upper.endswith(
        "MESSAGES.CSV"
    ):

        if isinstance(content, list):

            return [
                normalize_message(
                    source_file,
                    row,
                )
                for row in content
            ]

        return normalize_message(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # EMAIL
    # --------------------------------------------------------

    if extension == ".eml":
        return normalize_email(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # TRANSACTIONS
    # --------------------------------------------------------

    if (
        "\\TRANSACTION_EXPORTS\\"
        in source_upper
    ):

        if isinstance(content, list):

            return [
                normalize_transaction(
                    source_file,
                    row,
                )
                for row in content
            ]

        if isinstance(content, dict):

            transactions = content.get(
                "Transaction"
            )

            if isinstance(
                transactions,
                list,
            ):
                return [
                    normalize_transaction(
                        source_file,
                        row,
                    )
                    for row in transactions
                ]

            # Some extracted XML files
            # have an extra Transactions layer.

            transactions_container = content.get(
                "Transactions"
            )

            if isinstance(
                transactions_container,
                dict,
            ):

                transactions = (
                    transactions_container.get(
                        "Transaction"
                    )
                )

                if isinstance(
                    transactions,
                    list,
                ):
                    return [
                        normalize_transaction(
                            source_file,
                            row,
                        )
                        for row in transactions
                    ]

        return normalize_transaction(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # VEHICLE REGISTRY
    # --------------------------------------------------------

    if source_upper.endswith(
        "VEHICLE_REGISTRY.CSV"
    ):

        if isinstance(content, list):

            return [
                normalize_vehicle_registry(
                    source_file,
                    row,
                )
                for row in content
            ]

        return normalize_vehicle_registry(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # VEHICLE SIGHTINGS
    # --------------------------------------------------------

    if source_upper.endswith(
        "VEHICLE_SIGHTINGS.JSON"
    ):

        if isinstance(content, list):

            return [
                normalize_vehicle_sighting(
                    source_file,
                    row,
                )
                for row in content
            ]

        return normalize_vehicle_sighting(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # DEVICE EXTRACTION / GPS
    # --------------------------------------------------------

    if (
        "\\07_DEVICES\\"
        in source_upper
    ):
        return normalize_gps(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # GPS CSV
    # --------------------------------------------------------

    if source_upper.endswith(
        "GPS_POINTS.CSV"
    ):
        return normalize_gps_csv(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # ACCESS CONTROL
    # --------------------------------------------------------

    if (
        "\\09_ACCESS_SECURITY\\"
        in source_upper
    ):
        return normalize_access_log(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # CALENDAR / ICS
    # --------------------------------------------------------

    if extension == ".ics":
        return normalize_calendar_event(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # WITNESS MATERIAL
    # --------------------------------------------------------

    if (
        "\\02_WITNESS_MATERIAL\\"
        in source_upper
    ):
        return normalize_witness(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # FORENSICS
    # --------------------------------------------------------

    if (
        "\\10_FORENSICS\\"
        in source_upper
    ):
        return normalize_generic_document(
            source_file,
            content,
        )

    # --------------------------------------------------------
    # EVERYTHING ELSE
    # --------------------------------------------------------

    return normalize_generic_document(
        source_file,
        content,
    )


# ============================================================
# NORMALIZE COMPLETE FILE
# ============================================================

def normalize_file(
    input_path,
    output_path,
):

    with open(
        input_path,
        "r",
        encoding="utf-8",
    ) as f:

        records = json.load(f)

    normalized = []

    for record in records:

        try:

            result = normalize_record(
                record
            )

            for item in flatten(result):

                if item is not None:
                    normalized.append(item)

        except Exception as exc:

            normalized.append({
                "normalization_error": str(
                    exc
                ),
                "source_file": record.get(
                    "source_file"
                ),
            })

    output = {
        "metadata": {
            "source": str(
                input_path
            ),
            "record_count": len(
                normalized
            ),
            "evaluation_material_excluded": True,
        },
        "records": normalized,
    }

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        output_path,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            output,
            f,
            indent=2,
            ensure_ascii=False,
        )

    print(
        f"Normalized records: "
        f"{len(normalized)}"
    )

    print(
        f"Saved to: {output_path}"
    )


# ============================================================
# CLI
# ============================================================

if __name__ == "__main__":

    if len(sys.argv) < 2:

        print(
            "Usage: python "
            "-m ingestion.normalizers.universal_normalizer "
            "<extracted_evidence.json> "
            "[output.json]"
        )

        sys.exit(1)

    input_path = Path(
        sys.argv[1]
    )

    if len(sys.argv) >= 3:

        output_path = Path(
            sys.argv[2]
        )

    else:

        output_path = Path(
            "data/normalized_evidence.json"
        )

    if not input_path.exists():

        print(
            f"File does not exist: "
            f"{input_path}"
        )

        sys.exit(1)

    normalize_file(
        input_path,
        output_path,
    )